apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
    version: 1
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    url: https://elasticsearch:9200
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: /etc/grafana/elasticsearch-secrets/secrets/elastic_password.crt 
    jsonData:
      esVersion: 8.0.0
      timeField: "@timestamp"
      tlsAuth: true
      tlsAuthWithCACert: true
      caCert: "/etc/grafana/elasticsearch-certs/ca/ca.crt"
      serverName: "elasticsearch"
      sslSkipVerify: false
    version: 1