http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline


# --- NUEVO ---
#path.data: /usr/share/logstash/data
#path.logs: /usr/share/logstash/logs

# Configuración de memoria
#LS_JAVA_OPTS: -Xms512m -Xmx512m