#=======================================
# MEJORADO
#=======================================
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On 
SecDataDir /var/cache/modsecurity/
SecTmpDir /tmp/modsecurity/
SecAuditLog /var/log/modsec/modsec_audit.log
SecDebugLog /var/log/modsec/modsec_debug.log
SecDebugLogLevel 0
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLogStorageDir /var/log/modsec/

# Ajustar estos valores según tu hardware
#SecRequestBodyLimit 13107200
#SecRequestBodyNoFilesLimit 131072
#SecRequestBodyInMemoryLimit 131072
#SecPcreMatchLimit 100000
#SecPcreMatchLimitRecursion 100000

#=======================================
# ANTERIOR
#=======================================
#SecRuleEngine DetectionOnly
#SecRequestBodyAccess On
#SecResponseBodyAccess On
#SecDataDir /var/cache/modsecurity/
#SecTmpDir /tmp/modsecurity/
#SecAuditLog /var/log/modsec/modsec_audit.log
#SecDebugLog /var/log/modsec/modsec_debug.log
#SecDebugLogLevel 0
#SecAuditEngine RelevantOnly
#SecAuditLogRelevantStatus "^(?:5|4(?!04))"
#SecAuditLogParts ABIFHZ
#SecAuditLogType Serial
#SecAuditLogStorageDir /var/log/modsec/