SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On 
SecDataDir /var/cache/modsecurity/
SecTmpDir /tmp/modsecurity/
SecAuditLog /var/log/modsec/modsec_audit.log
SecDebugLog /var/log/modsec/modsec_debug.log
SecDebugLogLevel 0
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLogStorageDir /var/log/modsec/
SecRule ARGS|REQUEST_HEADERS "@detectXSS" "id:1001,deny,status:403,msg:'XSS Attack Detected'"
SecRule REQUEST_URI|REQUEST_BODY "@contains ../" "id:1002,phase:1,deny,status:403,msg:'Path Traversal Attack Detected',t:none,t:urlDecode,t:normalizePathWin,t:normalizePath"
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
SecComponentSignature "OWASP_CRS"

