SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecResponseBodyAccess On
SecDataDir /var/cache/modsecurity/
SecTmpDir /tmp/modsecurity/
SecAuditLog /var/log/modsec/modsec_audit.log
SecDebugLog /var/log/modsec/modsec_debug.log
SecDebugLogLevel 0
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIFHZ
SecAuditLogType Serial
SecAuditLogStorageDir /var/log/modsec/