# Cargar el módulo ModSecurity globalmente
load_module modules/ngx_http_modsecurity_module.so;

user  nginx;
worker_processes  1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Habilitar ModSecurity globalmente
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/modsecurity.conf;
    modsecurity_rules_file /etc/nginx/modsec/crs-setup.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/*.conf;

    server {
        listen 80;
        server_name localhost;
        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Manejo de archivos PHP
        location ~ \.php$ {
            include fastcgi_params;
            include snippets/fastcgi-php.conf;
            fastcgi_index index.php;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;  # Usar socket
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location /zap_reports {
            alias /zap/reports;
            autoindex on;
        }

        # Configuración adicional de seguridad
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "no-referrer-when-downgrade";
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self';";
    }
}
