apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
      - name: sqlite
        image: nouchka/sqlite3 # Imagen que contiene SQLite
        volumeMounts:
        - name: sqlite-data
          mountPath: /data/sqlite # Ruta donde se guardan los datos de SQLite
        resources:
          requests:
            memory: "256Mi"  # Especifica la memoria solicitada
            cpu: "250m"      # Especifica la CPU solicitada
          limits:
            memory: "512Mi"  # Especifica el límite de memoria
            cpu: "500m"      # Especifica el límite de CPU
      volumes:
      - name: sqlite-data
      persistentVolumeClaim:
          claimName: sqlite-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: sqlite
spec:
  selector:
    app: sqlite
  ports:
  - port: 80



