networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  sqlite:   # Base de datos (SQLite)
    build:
      context: ./dockers/sqlite/
      dockerfile: Dockerfile
    container_name: sqlite
    volumes:
      - sqlite_data:/var/lib/sqlite
    networks:
      - transcendence
    restart: on-failure

  backend:    # Backend (Node.js API)
    build: dockers/backend/.
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - backend_data:/usr/src/app/data
      - sqlite_data:/usr/src/app/data
      - sqlite_data:/var/lib/sqlite
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
      - security
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - TZ=Europe/Madrid
    env_file:
      - .env
    networks:
      - transcendence
    restart: unless-stopped

  php:
    build: dockers/php/.
    container_name: php
    volumes:
      - php_data:/var/www/html
      - zap_reports:/zap/reports
      - php_ssl:/etc/nginx/ssl
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    ports:
      - "8443:443"
      - "8080:80"
      - "9001:9001"
    networks:
      - transcendence
    depends_on:
      - frontend
      - security
    restart: always
  
  frontend:   # Frontend (TypeScript + Tailwind)
    build:
      context: ./dockers/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3040:3040"
    networks:
      - transcendence
    restart: unless-stopped
    depends_on:
      - backend

  security:
    build:
      context: ./dockers/frontend/
      dockerfile: Dockerfile
    container_name: security
    image: softwaresecurityproject/zap-stable
    ports:
      - "8081:8081"  # OWASP ZAP
      - "8200:8200"  # HashiCorp Vault
    env_file:
      - .env
    environment:
      - ZAP_DAEMON=True
      - ZAP_PORT=8081
      - ZAP_ALLOWED_HOSTS=*
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_SKIP_VERIFY=false
      - VAULT_CACERT=/etc/vault/tls/ca.crt
      - VAULT_ROLE_ID_FILE=/vault/data/role_id.txt
      - VAULT_SECRET_ID_FILE=/vault/data/secret_id.txt
    volumes:
      - zap_data:/zap/wrk          # Contiene todo el workspace de ZAP
      - zap_reports:/zap/reports    # Reportes de ZAP
      - vault_data:/vault/data      # Datos persistentes de Vault
      - tls_volume:/etc/vault/tls   # Certificados TLS (única ubicación)
    networks:
      transcendence:
        aliases:
          - security
    restart: unless-stopped


  mailserver:
    build: dockers/mailserver/.
    image: namshi/smtp
    container_name: mailserver
    environment:
      - RELAY_NETWORKS=172.16.0.0/16
      - MYNETWORKS=172.16.0.0/16
      - DISABLE_AUTH=true
      - DISABLE_TLS=true
    networks:
      - transcendence
    ports:
      - "1080:1080" # Web interface
      - "1025:25" # SMTP port

volumes:
  sqlite_data:
    name: sqlite_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/sqlite"
      o: bind
  
  backend_data:
    name: backend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/app"
      o: bind
  
  frontend_data:
    name: frontend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/frontend"
      o: bind

  php_data:
    name: php_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/php"
      o: bind
  
  php_ssl:
    name: php_ssl
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/php"
    
  zap_data:
     name: zap_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind
  
  zap_reports:
     name: zap_reports
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind

  vault_data:
     name: vault_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/vault"
       o: bind
       #o: bind,uid=65534,gid=65534,mode=0777
  
  tls_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/vault"
  
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/grafana"
  
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/prometheus"
  
  mail_data:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/mail"
      o: bind
  
  mail_state:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/mail-state"
      o: bind
  
  es_secrets:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/es_secrets"
      o: bind
  
  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/elasticsearch"
  
  es_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/es_certs"
  
  ls_config:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/ls_config"
      o: bind
  
  ls_pipeline:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/ls_pipeline"
      o: bind