networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  sqlite:   # Base de datos (SQLite)
    build: dockers/sqlite/.
    container_name: sqlite
    image: nouchka/sqlite3  # Imagen de SQLite para acceder a la base de datos
    volumes:
      - sqlite_data:/var/lib/sqlite
    networks:
      - transcendence
    restart: on-failure

  backend:    # Backend (Node.js API)
    build: dockers/backend/.
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - backend_data:/usr/src/app/data
      - sqlite_data:/usr/src/app/data
      - sqlite_data:/var/lib/sqlite
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
      - avalanche
      - security
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    #  - VAULT_TOKEN="${ROOT_TOKEN}"
    env_file:
      - .env
    networks:
      - transcendence
    restart: unless-stopped

  php:
    build: dockers/php/.
    container_name: php
    volumes:
      - php_data:/var/www/html
      - zap_reports:/zap/reports
      - php_ssl:/etc/nginx/ssl
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    ports:
      - "443:443"
      - "8080:80"
      - "9001:9001"
    networks:
      - transcendence
    depends_on:
      - frontend
      - security
    restart: always

  frontend:   # Frontend (TypeScript + Tailwind)
    build: dockers/frontend/.
    container_name: frontend
    image: node:18-alpine
    volumes:
      - frontend_data:/usr/src/app      # Volumen para el código fuente
      - php_data:/usr/src/app/dist   # Comparte los archivos estáticos con PHP
    command: sh -c "npm run build && npx serve dist -l 3001"  # Cambiado a `npm run build` para generar archivos estáticos
    ports:
      - "3001:3001"
    networks:
      - transcendence
    restart: unless-stopped
    depends_on:
      - backend

  avalanche:      # Blockchain (Avalanche)
    build: dockers/blockchain/.
    container_name: blockchain
    volumes:
      - blockchain_data:/avalanchego
      - ./dockers/blockchain/config.json:/avalanchego/config.json
    ports:
      - "9650:9650"   # JSON RPC endpoint
      - "9651:9651"   # P2P port
    command: ["/avalanchego/avalanchego", "--data-dir", "/avalanchego", "--http-host=0.0.0.0"]
    networks:
      - transcendence
    restart: unless-stopped

  security:
    build: dockers/security/.
    container_name: security
    image: softwaresecurityproject/zap-stable
    ports:
      - "8081:8081"  # OWASP ZAP
      - "8200:8200"  # HashiCorp Vault
    env_file:
      - .env
    environment:
      - ZAP_DAEMON=True
      - ZAP_PORT=8081
      - ZAP_ALLOWED_HOSTS=*
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_SKIP_VERIFY=false
      - VAULT_CACERT=/etc/vault/tls/ca.crt
      - VAULT_ROLE_ID_FILE=/vault/data/role_id.txt
      - VAULT_SECRET_ID_FILE=/vault/data/secret_id.txt
    #user: "1001:1001"
    #cap_add:
    #  - IPC_LOCK
    volumes:
      - zap_data:/zap/wrk          # Contiene todo el workspace de ZAP
      - zap_reports:/zap/reports    # Reportes de ZAP
      - vault_data:/vault/data      # Datos persistentes de Vault
      - tls_volume:/etc/vault/tls   # Certificados TLS (única ubicación)
    entrypoint: ["/zap/wrk/entrypoint.sh"]
    networks:
      transcendence:
        aliases:
          - security
    restart: unless-stopped

  elasticsearch:
    build: ./dockers/management/elasticsearch
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Desactivar seguridad para desarrollo local
      - ES_JAVA_OPTS=-Xms1g -Xmx1g    # Ajustar memoria según sistema
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - transcendence
    restart: unless-stopped

  logstash:
    build: ./dockers/management/logstash
    image: logstash:8.12.0
    container_name: logstash
    volumes:
      - ls_data:/usr/share/logstash/pipeline  # Configuración de pipelines
      - ls_data:/usr/share/logstash/config      # Configuración adicional
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    depends_on:
      - elasticsearch
    networks:
      - transcendence
    restart: unless-stopped

  kibana:
    build: ./dockers/management/kibana
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - transcendence
    restart: unless-stopped

  prometheus:
    build: ./dockers/monitoring/prometheus
    image: prom/prometheus
    container_name: prometheus
    user: "nobody"  # Asegurar que corre como usuario no privilegiado
    volumes:
      - prometheus_data:/prometheus
      - ./dockers/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - transcendence
    restart: unless-stopped

  grafana:
    build: ./dockers/monitoring/grafana
    image: grafana/grafana
    container_name: grafana
    user: "472"  # Usuario grafana por defecto (UID 472)
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dockers/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./dockers/monitoring/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3003:3000"  # Grafana usa el puerto 3000 por defecto
    depends_on:
      - prometheus
    networks:
      - transcendence
    restart: unless-stopped

  # --- SECCIÓN DEVOPS ---------------------
  # Microservicios (Backend Reestructurado)

 # auth-service:
 #   build: ./microservices/auth
 #   ports:
 #     - "3002:3000"
 #   networks:
 #     - transcendence
 #   depends_on:
 #     - sqlite

 # user-service:
 #   build: ./microservices/users
 #   ports:
 #     - "3003:3000"
 #   networks:
 #     - transcendence

 # blockchain-service:
 #   build: ./microservices/blockchain
 #   ports:
 #     - "3004:3000"
 #   networks:
 #     - transcendence

volumes:
  sqlite_data:
    name: sqlite_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/sqlite"
      o: bind
  
  backend_data:
    name: backend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/app"
      o: bind
  
  frontend_data:
    name: frontend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/frontend"
      o: bind
  
  blockchain_data:
    name: blockchain_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/blockchain"
      o: bind

  php_data:
    name: php_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/php"
      o: bind
  
  php_ssl:
    name: php_ssl
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/php"
    
  zap_data:
     name: zap_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind
  
  zap_reports:
     name: zap_reports
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind

  vault_data:
     name: vault_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/vault"
       o: bind
  
  tls_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/vault"

  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/elasticsearch"
  
  ls_data:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/logstash"
      o: bind
  
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/grafana"
  
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/prometheus"
  