networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  sqlite:   # Base de datos (SQLite)
    build: dockers/sqlite/.
    container_name: sqlite
    image: nouchka/sqlite3  # Imagen de SQLite para acceder a la base de datos
    volumes:
      - sqlite_data:/var/lib/sqlite
    networks:
      - transcendence
    restart: on-failure

  backend:    # Backend (Node.js API)
    build: dockers/backend/.
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - backend_data:/usr/src/app/data
      - sqlite_data:/usr/src/app/data
      - sqlite_data:/var/lib/sqlite
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
      - security
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - TZ=Europe/Madrid
    env_file:
      - .env
    networks:
      - transcendence
    restart: unless-stopped

  chat-service:
    build:
      context: ./dockers/chat-service/
      dockerfile: Dockerfile
    container_name: chat-service
    env_file:
      - .env
    ports:
      - "3050:3050"
    networks:
      - transcendence

  php:
    build: dockers/php/.
    container_name: php
    volumes:
      - php_data:/var/www/html
      - zap_reports:/zap/reports
      - php_ssl:/etc/nginx/ssl
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    ports:
      - "8443:443"
      - "8080:80"
      #- "9001:9001"
    networks:
      - transcendence
    depends_on:
      - frontend
      - security
    restart: always
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - '-nginx.scrape-uri=http://php:8080/nginx_status'
    ports:
      - "9113:9113"
    networks:
      - transcendence
    depends_on:
      - php
  
  php-fpm-exporter:
    image: hipages/php-fpm_exporter:latest
    container_name: php-fpm-exporter
    environment:
      - PHP_FPM_SCRAPE_URI=tcp://php-nginx:9001/status
    ports:
      - "9253:9253"
    depends_on:
      - php
    networks:
      - transcendence


  frontend:   # Frontend (TypeScript + Tailwind)
    build: dockers/frontend/.
    container_name: frontend
    image: node:18-alpine
    volumes:
      - frontend_data:/usr/src/app      # Volumen para el código fuente
      - php_data:/usr/src/app/dist   # Comparte los archivos estáticos con PHP
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./ssl_certs:/etc/nginx/ssl:ro
    command: sh -c "npm run build && npx serve dist -l 3040"  # Cambiado a `npm run build` para generar archivos estáticos
    ports:
      - "3040:3040"
    networks:
      - transcendence
    restart: unless-stopped
    depends_on:
      - backend

  security:
    build: dockers/security/.
    container_name: security
    image: softwaresecurityproject/zap-stable
    ports:
      - "8081:8081"  # OWASP ZAP
      - "8200:8200"  # HashiCorp Vault
    env_file:
      - .env
    environment:
      - ZAP_DAEMON=True
      - ZAP_PORT=8081
      - ZAP_ALLOWED_HOSTS=*
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_SKIP_VERIFY=false
      - VAULT_CACERT=/etc/vault/tls/ca.crt
      - VAULT_ROLE_ID_FILE=/vault/data/role_id.txt
      - VAULT_SECRET_ID_FILE=/vault/data/secret_id.txt
    volumes:
      - zap_data:/zap/wrk          # Contiene todo el workspace de ZAP
      - zap_reports:/zap/reports    # Reportes de ZAP
      - vault_data:/vault/data      # Datos persistentes de Vault
      - tls_volume:/etc/vault/tls   # Certificados TLS (única ubicación)
    entrypoint: ["/zap/wrk/entrypoint.sh"]
    networks:
      transcendence:
        aliases:
          - security
    restart: unless-stopped
    mem_limit: 1.5GB 
    mem_reservation: 512MB
    healthcheck:
      test: ["CMD", "sh", "-c", "vault status -tls-skip-verify && test -s /vault/data/ui_token.txt && echo 'Vault ready and token present'"]
      interval: 10s
      timeout: 5s
      retries: 20 # Número de reintentos antes de considerar el contenedor unhealthy
      start_period: 30s # Tiempo para que el contenedor inicie antes de que healthcheck comience a contar fallos

  elasticsearch:
    build: ./dockers/management/elasticsearch
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.transport.ssl.enabled=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_secrets:/usr/share/elasticsearch/secrets
      - es_certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9200:9200"
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:9200/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 5s
      retries: 30

  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch_exporter
    ports:
      - "9114:9114"
    environment:
      - ES_URI=https://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD_FILE=/usr/share/elasticsearch/secrets/elastic_password
      - ES_CA=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - ES_ALL=true
      - ES_TIMEOUT=30s
    volumes:
      - es_certs:/usr/share/elasticsearch/config/certs:ro
      - es_secrets:/usr/share/elasticsearch/secrets:ro
    networks:
      - transcendence

  logstash:
    build: ./dockers/management/logstash
    image: logstash:8.12.0
    container_name: logstash
    restart: on-failure
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD_FILE=/usr/share/elasticsearch/secrets/elastic_password
      - XPACK_MONITORING_ENABLED=false 
    volumes:
      - es_secrets:/usr/share/elasticsearch/secrets
      - es_certs:/usr/share/elasticsearch/config/certs
      - ls_config:/usr/share/logstash/config
      - ls_pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"   # Entrada Beats
      - "8082:8082"   # Métricas Prometheus
    depends_on:
      - elasticsearch
    networks:
      - transcendence
  
  logstash-exporter:
    build: ./dockers/management/logstash-exporter
    container_name: logstash-exporter
    restart: unless-stopped
    depends_on:
      - logstash
    environment:
      - LOGSTASH_URL=https://logstash:9600/_node/stats
      - VERIFY_SSL=false
    ports:
      - "9811:9811"
    networks:
      - transcendence

  kibana:
    build: ./dockers/management/kibana
    image: kibana:8.12.0
    container_name: kibana
    restart: on-failure
    volumes:
      - es_secrets:/usr/share/elasticsearch/secrets
      - es_certs:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - transcendence

  kibana-exporter:
    build: ./dockers/management/kibana-exporter
    container_name: kibana-exporter
    environment:
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_USERNAME=elastic
      - KIBANA_PASSWORD_FILE=/usr/share/elasticsearch/secrets/elastic_password
      - INSECURE_SKIP_VERIFY=true
    volumes:
      - es_secrets:/usr/share/elasticsearch/secrets
      - es_certs:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "9201:9201"
    depends_on:
      - kibana
    networks:
      - transcendence
  
  prometheus:
    build: ./dockers/monitoring/prometheus
    image: prom/prometheus
    container_name: prometheus
    user: "65534:65534"
    cap_add:
      - CAP_NET_RAW
    volumes:
      - prometheus_data:/prometheus
      - prometheus_query_log:/data
      - ./dockers/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./dockers/monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./dockers/monitoring/prometheus/web-config.yml:/etc/prometheus/web-config.yml
      - vault_data:/vault/data
      - tls_volume:/etc/vault/tls
      - es_data:/usr/share/elasticsearch/data
      - es_secrets:/usr/share/elasticsearch/secrets
      - es_certs:/usr/share/elasticsearch/config/certs
      - es_certs:/etc/prometheus/ssl
    command:
      - '--web.config.file=/etc/prometheus/web-config.yml'
    environment:
      - UID=65534
      - GID=65534
    ports:
      - "9090:9090"
    networks:
      - transcendence
    restart: unless-stopped

  grafana:
    build: ./dockers/monitoring/grafana
    image: grafana/grafana
    container_name: grafana
    user: "472"  # Usuario grafana por defecto (UID 472)
    volumes:
      - grafana_data:/var/lib/grafana
      - prometheus_data:/prometheus/certs:ro
      - es_data:/usr/share/elasticsearch/data
      - es_certs:/etc/grafana/elasticsearch-certs
      - es_secrets:/etc/grafana/elasticsearch-secrets
      - ./dockers/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./dockers/monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3003:3000"  # Grafana usa el puerto 3000 por defecto
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/grafana.key
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    depends_on:
      - prometheus
      - elasticsearch
    networks:
      - transcendence
    restart: unless-stopped

  mailserver:
    build: dockers/mailserver/.
    image: namshi/smtp
    container_name: mailserver
    environment:
      - RELAY_NETWORKS=172.16.0.0/16
      - MYNETWORKS=172.16.0.0/16
      - DISABLE_AUTH=true
      - DISABLE_TLS=true
    networks:
      - transcendence
    ports:
      - "1080:1080" # Web interface
      - "1025:25" # SMTP port

volumes:
  sqlite_data:
    name: sqlite_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/sqlite"
      o: bind
  
  backend_data:
    name: backend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/app"
      o: bind
  
  frontend_data:
    name: frontend_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/frontend"
      o: bind

  php_data:
    name: php_data
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/php"
      o: bind
  
  php_ssl:
    name: php_ssl
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/php"
    
  zap_data:
     name: zap_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind
  
  zap_reports:
     name: zap_reports
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/security"
       o: bind

  vault_data:
     name: vault_data
     driver: local
     driver_opts:
       type: none
       device: "$HOME/goinfre/data/vault"
       o: bind
       #o: bind,uid=65534,gid=65534,mode=0777
  
  tls_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/vault"
  
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/grafana"
  
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/prometheus"

  prometheus_query_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/prometheus"
  
  mail_data:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/mail"
      o: bind
  
  mail_state:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/mail-state"
      o: bind
  
  es_secrets:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/es_secrets"
      o: bind
  
  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/elasticsearch"
  
  es_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/goinfre/data/es_certs"
  
  ls_config:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/ls_config"
      o: bind
  
  ls_pipeline:
    driver: local
    driver_opts:
      type: none
      device: "$HOME/goinfre/data/ls_pipeline"
      o: bind